'use strict';

const ExamStatus = {
  DRAFT: 'DRAFT',
  REVIEW: 'REVIEW',
  PUBLISHED: 'PUBLISHED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED'
};

const AttemptStatus = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  AUTO_SUBMITTED: 'AUTO_SUBMITTED',
  SUBMITTED: 'SUBMITTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  UNDER_REVIEW: 'UNDER_REVIEW'
};

const ResultReleasePolicy = {
  IMMEDIATE: 'IMMEDIATE',
  MANUAL: 'MANUAL',
  SCHEDULED: 'SCHEDULED',
  AFTER_ALL_FINISHED: 'AFTER_ALL_FINISHED',
  AFTER_DEADLINE: 'AFTER_DEADLINE'
};

const ProctorSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
};

const SectionType = {
  MCQ: 'MCQ',
  DESCRIPTIVE: 'DESCRIPTIVE',
  CODING: 'CODING'
};

const EventTypes = {
  ATTEMPT_STARTED: 'ATTEMPT_STARTED',
  ATTEMPT_RESUMED: 'ATTEMPT_RESUMED',
  QUESTION_VISITED: 'QUESTION_VISITED',
  ANSWER_SAVED: 'ANSWER_SAVED',
  CODE_RUN_QUEUED: 'CODE_RUN_QUEUED',
  CODE_RUN_FINISHED: 'CODE_RUN_FINISHED',
  CODE_SUBMIT_QUEUED: 'CODE_SUBMIT_QUEUED',
  CODE_SUBMIT_FINISHED: 'CODE_SUBMIT_FINISHED',
  AUTO_SAVE: 'AUTO_SAVE',
  SUBMIT: 'SUBMIT',
  TIMEOUT: 'TIMEOUT',
  GRADE_UPDATED: 'GRADE_UPDATED',
  PROCTOR_INCIDENT: 'PROCTOR_INCIDENT'
};

module.exports = {
  ExamStatus,
  AttemptStatus,
  ResultReleasePolicy,
  ProctorSeverity,
  SectionType,
  EventTypes
};
